config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories

  post "/reactions", to: "reactions#user_reaction", as: "user_reaction"
  get "/my_reactions", to: "reactions#product_with_reactions", as: "my_reactions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!

  def user_reaction
    @user = current_user
    @product = Product.find(params[:product_id])
    reaction = Reaction.find_by(user_id: @user.id, product_id: @product.id)
    if reaction
      flash.now[:alert] = "You already reacted to this product"
    else
      @new_reaction = Reaction.new(user_id: @user.id, product_id: @product.id, kind: params[:kind])
      respond_to do |format|
        if @new_reaction.save!
          format.html { redirect_to product_path(@product), notice: "#{current_user.email} has stated that it #{@new_reaction.kind}
the product" }
        else
          format.html { redirect_to product_path(@product), status: :unprocessable_entity }
        end
      end
    end
  end

  def product_with_reactions
    @reactions = current_user.reactions
    product_ids = @reactions.map(&:product_id)
    @products = Product.where(id: product_ids)
  end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_counters.html.erb
<%# <div class="container">
    <ul>
        <% Reaction.kinds.each do |kind| <>>
            <li> <%= @product.reactions.where(kind: kind).count <>> - <%= kind <>> </li>
        <% end <>>
    </ul>
</div> %>


<div class="container">
    <ul>
        <% Reaction.kinds.each do |kind| %>
            <li> <%= @product.count_with_kind(kind) %> </li>
        <% end %>
    </ul>
</div>

app/views/reactions/_options.html.erb
<div class="container">
    <ul>
        <% Reaction.kinds.each do |kind| %>
            <li><%= button_to "#{kind}", user_reaction_path(product_id: @product.id, kind: kind), method: :post %></li>
        <% end %>
    </ul>
</div>

app/views/reactions/product_with_reactions.html.erb
<%# <h1>Products</h1>
<ul>
    <% @products.each do |product| <>>
        <li>
            <%= product.name <>> 
            <%= product.reactions.find_by(user_id: current_user.id).kind <>>
            <p>
                <%= link_to "Show this product", product <>>
            </p>
        </li>
    <% end <>>
</ul> %>

<h1>Products</h1>
<ul>
    <% @products.each do |product| %>
        <li>
            <%= product.name %> 
            <%= product.find_kind_user_relation(current_user) %>
            <p>
                <%= link_to "Show this product", product %>
            </p>
        </li>
    <% end %>
</ul>