config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories

  post "/reactions", to: "reactions#user_reaction", as: "user_reaction"
  get "/my_reactions", to: "reactions#product_with_reactions", as: "my_reactions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/views/shared/_navbar.html.erb
<nav class="mx-auto navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <%= link_to "Products", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="nav-item mx-2">
                <%= link_to "Categories", categories_path, class:"nav-link active", ariaCurrent: "page" %>
            </div>
            <% if user_signed_in? %>
                <div class="nav-item mx-2">
                    <%= link_to 'Tus reacciones', my_reactions_path, class: 'nav-link' %>
                </div>
            <% end %>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Usuarios</a>
                            <% if current_user %>
                            Hola <%= current_user.email %>
                            <% else %>
                            Dale registrate o conectate
                            <% end %>
                        <ul class="dropdown-menu">
                            <% if user_signed_in? %>
                                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                            <% else %>
                                <li><%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%></li>
                            <% end %>  
                        </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>