config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories

  post "/reactions", to: "reactions#user_reaction", as: "user_reaction"
  get "/my_reactions", to: "reactions#product_with_reactions", as: "my_reactions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  has_many :reactions, dependent: :destroy
  has_many :users, through: :reactions

  accepts_nested_attributes_for :categories, reject_if: :no_name_category

  validates :name, presence: true
  validates :price, presence: true
  validates :size, presence: true

  def count_with_kind(arg)
    number = self.reactions.where(kind: arg).count
    return "#{arg} - #{number}" # rubocop:disable Style/RedundantReturn
  end


  def find_kind_user_relation(user)
    self.reactions.find_by(user_id: user.id).kind
  end


  def no_name_category(attributes)
    attributes["name"].blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_categories, only: %i[ new edit create update]
  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.categories.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    def set_categories
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    # def product_params
    #   params.expect(product: [ :name, :price, :size, category_ids: [] ])
    # end

    def product_params
      params.require(:product).permit(:name, :price, :size, { category_ids: [] }, categories_attributes: [ :id, :name ])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container form-group">
  <div>
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block", class:"form-label" %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div>
    <%= form.label :size, style: "display: block", class:"form-label" %>
    <%= form.number_field :size, class:"form-control" %>
  </div>



  <div>
    <%= form.label :category_ids, style: "display: block", class: "form-group" %>
      <div class="row">
        <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) do |b|%>
            <div class="col-md-2">
              <span class="w100 form-control my-2"><%= b.label { b.check_box + " " + b.text } %></span>
            </div>
        <% end %>
      </div>
  </div>


<%# SIN BOOTSTRAP
  <div>
    <%= form.label :category_ids, style: "display: block" <>>
    <%= form.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| <>>
        <div>
          <span> <%= b.label {b.check_box + "  " + b.text} <>> </span>
        </div> 
    <% end <>>
  </div> %>
<br><hr><br>
<% if action_name == 'new' %>
  <%= form.fields_for :categories do |ff| %>
    <div class= "form-group">
      <%= ff.label :name, "Category Name", class:"form-label" %>
      <%= ff.text_field :name, class: "form-control" %>
    </div>
  <% end %>
<% end %>
<br>
    
<div>
  <%= form.submit %>
  <% end %>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= product.size %>
  </p>


  <strong>Category: </strong>
    <% product.categories.each do |category| %>
      <p><%= category.name %></p>
    <% end %>

</div>

app/views/products/_show_categories.html.erb
<div class="row">
    <div class="col-md-6">
        <%= render @product %>
    </div>
    <div class="col-md-6">
        <ol class="list-group list-group-numbered">
            <% @product.categories.each do |pc| %>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold"><%= pc.name %></div>
                        <span class="badge bg-primary rounded-pill"><%= pc.products.count %></span>
                    </div>
                </li>
            <% end %>
        </ol>
    </div>
</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div class="container">
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
  <%= render 'products/show_categories' %>
</div>
<div>
  <%= render 'reactions/options' %>
</div>
<div>
  <%= render 'reactions/counters' %>
</div>

<div class="container">
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>
</div>
  <br>
<div class="container">
  <%= button_to "Destroy this product", @product, method: :delete %>
</div>